#pragma once

enum TYPE_MSG
{
	MESSAGE_ERROR,
	CLIENT_REQUEST_LOGIN,
	SERVER_REPLY_LOGIN,
	CLIENT_REQUEST_PLAY,
	SERVER_REPLY_PLAY,
	CLIENT_REQUEST_LOGOUT,
	SERVER_REPLY_LOGOUT,
	SERVER_SEND_QUESTION_BEGIN,
	CLIENT_ANSWER_QUESTION_BEGIN,
	SERVER_ANSWER_QUESTION_BEGIN,
	SERVER_SEND_QUESTION,
	CLIENT_ANSWER_QUESTION,
	SERVER_ANSWER_QUESTION,
	CLIENT_USE_HELP_50_50,
	SERVER_ANSWER_HELP_50_50,
	CLIENT_USE_HELP_CALL,
	SERVER_ANSWER_HELP_CALL,
	CLIENT_USE_HELP_ASK_AUDIENCE,
	SERVER_ANSWER_HELP_AUDIENCE,
	CLIENT_USE_HELP_ADVISORY,
	SERVER_ANSWER_HELP_ADVISORY,	
	SERVER_NEWS,					// thông báo hoạt động cho các player phụ
	CLIENT_WANT_END_GAME,
	SERVER_ACCEPT_END_GAME,
	CLIENT_WANT_QUIT,
	SERVER_ERROR,
	CLIENT_ERROR
};

enum STEP_GAME
{
	LOGIN,
	WAIT,
	QUESTION_BEGIN,
	PLAY,						
	STREAM,
	HELP
};